os: linux
sudo: false
language: python

env:
  - CXX=g++
  - CXX=clang++
python:
  - "2.7"
  - "3.4"

cache:
  directories:
    - llvm-3.8.0
    - cmake
    - miniconda

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9

script:
  - export BASEDIR=`pwd`
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [ -z "$(ls -A cmake)" ]; then
        CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-rc2-Linux-x86_64.tar.gz";
        mkdir -p cmake;
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake;
      fi;
      export PATH=${BASEDIR}/cmake/bin:${PATH};
    else
      brew install cmake;
    fi;
  -
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export LLVM_VERSION=3.8.0;
      if [ -z "$(ls -A llvm-$LLVM_VERSION)" ]; then
        wget -O llvm-$LLVM_VERSION.tar.xz http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
        mkdir llvm-$LLVM_VERSION;
        xzcat llvm-$LLVM_VERSION.tar.xz | tar -xvf - --strip 1 -C llvm-$LLVM_VERSION;
      fi;
      llvm-$LLVM_VERSION/bin/llvm-config --version;
      export LLVM_CONFIG="llvm-$LLVM_VERSION/bin/llvm-config";
    fi;
    export LD_LIBRARY_PATH=$BASEDIR/llvm-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
  - if [ -z "$(ls -A miniconda)" ]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
      rm -rf $BASEDIR/miniconda;
      bash miniconda.sh -b -p $BASEDIR/miniconda;
    fi
  - export PATH=$BASEDIR/miniconda/bin:${PATH}
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - conda install -c ilastik vigra
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; export CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=$BASEDIR/llvm-$LLVM_VERSION/bin/clang++; export CC=$BASEDIR/llvm-$LLVM_VERSION/bin/clang; fi
  - mkdir build
  - cd build
  - mkdir -p install_dir
  - cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install_dir ..
  - make VERBOSE=1
  - make install
  - ctest --verbose

after_failure:
  - cat build/config.log
